version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      description: Python 3 using Jupyter Notebooks
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents/notebooks:/src/notebooks
    build: . 