version: '3'
services:
  notebook:
    image: jupyter_notebook
    container_name: jupter_notebook_anbu
    labels:
      description: Python 3 using Jupyter Notebooks
      name: jupyter notebook
    ports:
      - "4321:4321"
    volumes:
      - ~/Jupyter_Docker/notebooks:/src/notebooks
    build:
         .